apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-vite-react.fullname" . }}
  namespace: '{{ .Values.namespace }}'
  labels:
    {{- include "helm-vite-react.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appName }}
    tier: frontend
